config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/confirmation/resend", to: "users/confirmations#resend", as: :resend_confirmation
    get "users/confirmation/confirm", to: "users/confirmations#confirm", as: :confirm_confirmation
    get "users/password/reset_password", to: "users/passwords#reset_password", as: :reset_password
    get "users/registration/edit_user", to: "users/registrations#edit_user", as: :edit_user
    get "users/registration/edit_city", to: "users/registrations#edit_city", as: :edit_city
    delete "/users/unlink_google_account", to: "users/omniauth_callbacks#unlink_google_account", as: :unlink_google_account
  end
  resource :users, only: [ :show, :edit, :destroy, :update ] do
    get "profile", to: "users#show", as: "profile"
    get "reminder", to: "users#reminder", as: "reminder"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/home/privacy", to: "home#privacy", as: :privacy
  get "/home/rules", to: "home#rules", as: :rules
  get "colors/top" => "colors#top"

  resources :colors do
  collection do
    get "/colors/form", to: "colors#form", as: :form
  end
end

  resources :self_logs, only: [ :index, :show, :create, :destroy ] do
    member do
      get :ai_response
    end
    resources :weather_logs, only: [ :index, :show, :create, :destroy ]
    # get "colors/:id/response", to: "colors#response", as: :response
  end
  resources :analysis_results, only: [ :index, :show, :create, :destroy ]

  # chatbot機能
  get "chatbots/ask" => "chatbots#ask"
  post "chatbots/answer" => "chatbots#answer"

  # OpenWeatherAPI機能のルーティング
  get "weather", to: "weathers#index", as: :weather
  get "weather/show", to: "weathers#show", as: :show_weather, defaults: { format: :json }

  # JSからheatmap_dataへのエンドポイント
  get "heatmap", to: "result_maps#heatmap_data", as: :heatmap
  # JSからradar_map_dataへのエンドポイント
  get "map", to: "result_maps#map_data", as: :map
  # JSからopen AI へのエンドポイント
  post "/colors/analyze", to: "colors#analyze"
  # LINEルーティング
  post "/callback", to: "line#callback", as: :callback

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_line_token
  extend Enumerize

  has_many :self_logs
  has_many :colors, through: :self_logs, dependent: :destroy
  has_many :responses, through: :self_logs, dependent: :destroy
  has_many :weather_logs, through: :self_logs, dependent: :destroy

  validates :name, presence: true
  validates :prefecture, presence: true

  validates :password, presence: true, on: :create
  validates :password, presence: true, length: { minimum: 6 }, allow_blank: true
  validates :email, presence: { message: "メールアドレスの入力は必須です" }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :trackable, :confirmable,
          :timeoutable, :omniauthable, omniauth_providers: [ :google_oauth2 ]

  enum :line_alert, { no_alert: 0, need_alert: 1 }, validate: true

  def need_unconfirmed?
    pending_any_confirmation
  end

  def password_required?
    new_record? || password.present? || password_confirmation.present?
  end

  def self.from_omniauth(auth)
      data = auth.info
      user = User.find_by(email: data["email"])

    if user.blank?
      user = nil
      ActiveRecord::Base.transaction do
          user = User.new(
          email: auth.info.email,
          name: auth.info.name,
          password: Devise.friendly_token[0, 20],
          confirmed_at: Time.current,
          provider: auth.provider,
          uid: auth.uid,
          prefecture: "東京都" # デフォルト値
          )
          user.save!
      end
    end
      user
  end

    enumerize :prefecture, in: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47
  }, scope: true, predicates: true

  private

  def generate_line_token
    self.line_token = loop do
      random_token  = SecureRandom.hex(6)
      break random_token unless User.exists?(line_token: random_token)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    def resend
      self.resource = User.find_by(email: params[:user][:email])
      if resource&.need_unconfirmed?
        resource.send_confirmation_instructions
          flash[:notice] = "認証メールを送信しました!!"
            if request.referer&.include?("sign_in")
              redirect_to new_session_path(resource_name)
            elsif request.referer&.include?("sign_up")
              redirect_to new_registration_path(resource_name)
            end
      else
          flash[:alert] = "メールアドレスが見つからないか、すでに認証済みです"
            if request.referer&.include?("sign_in")
              redirect_to new_session_path(resource_name)
            elsif request.referer&.include?("sign_up")
              redirect_to new_registration_path(resource_name)
            end
      end
    end

    def confirm
      self.resource = resource_class.new
      respond_to do |format|
        format.turbo_stream
      end
    end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: :google_oauth2
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  def google_oauth2
    auth = request.env["omniauth.auth"]
    type = request.env["omniauth.params"]["type"]

  # Googleアカウント情報を署名付きCookieに保存（有効期限1時間）
  cookies.signed[:google_auth_data] = {
    value: {
      email: auth.info.email,
      provider: auth.provider,
      uid: auth.uid
    }.to_json,
    expires: 1.month.from_now,
    httponly: true,
    secure: Rails.env.production?
  }

    if type == "link"
      handle_google_link(auth)
    else
      handle_google_login(auth)
    end
  end

  def unlink_google_account
    data = cookies.signed[:google_auth_data]
    data = JSON.parse(data, symbolize_names: true) if data.present?

    if data.present?
      user = User.find_by(email: data[:email])
      if user
        user.update(provider: nil, uid: nil)
        cookies.delete(:google_auth_data)

        flash[:notice] = "Googleアカウントの連携を解除しました"
        cookies[:login_method] = "normal"
        redirect_to new_session_path(resource_name)
      else
        flash[:alert] = "ユーザーが見つかりません"
        redirect_to new_registration_path(resource_name)
      end
    else
      flash[:alert] = "連携解除のためには一度ログインからやり直してください"
      redirect_to new_session_path(resource_name)
    end
  end

  def failure
    cookies[:login_method] = "normal"
    redirect_to root_path, alert: "認証に失敗しました、一度Googleのログインをやり直してください"
  end

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  private

  def auth
    auth = request.env["omniauth.auth"]
  end

  def handle_google_link(auth)
    session[:google_auth_data] = {
      provider: auth.provider,
      uid: auth.uid,
      name: auth.info.name,
      email: auth.info.email
    }
    data = session[:google_auth_data]
    user = User.find_by(email: auth.info.email)
    begin
      if user && data.present?
        user.update!(provider: data[:provider], uid: data[:uid])
        cookies[:login_method] = "google"
        flash[:notice] = "Googleアカウントが連携されました。\n 以後、ログインの時はGoogleログインすることができます。"
      else
        flash[:notice] = "Googleアカウントの連携に失敗しました"
      end
    rescue => e
      flash[:alert] = "予期せぬエラーが発生しました。"
      Rails.logger.error("Googleアカウント連携エラー: #{e.message}")
    end
    render inline:
    <<~HTML
      <script>
        window.opener.location.reload();  // 親画面のリロード
        window.close();
      </script>
    HTML
  end

  def handle_google_login(auth)
    Rails.logger.info "Session data before processing: #{session.inspect}"

    @user = User.from_omniauth(auth)
    if @user.persisted?

      sign_in_and_redirect @user, event: :authentication
      cookies[:login_method] = resource.provider.present? ? "google" : "normal"
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra)
      redirect_to new_user_session_path, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  skip_before_action :require_no_authentication, only: [ :new, :create, :edit, :update, :reset_password ]

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  def create
    self.resource = User.find_by(email: params[:user][:email])

   if resource.present?
    super
    flash[:notice] = "パスワードリセットのメールを送信しました"
   else
    flash[:alert] = "メールアドレスが未入力です"
    redirect_to new_session_path(resource_name)
   end
  end

  def reset_password
    self.resource = resource_class.new
    respond_to do |format|
      format.turbo_stream
    end
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  def after_resetting_password_path_for(resource)
    if user_signed_in?
      flash[:notice] = "パスワードが変更されました"
      profile_users_path(current_user)
    else
      new_session_path(resource_name)
    end
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    if user_signed_in?
      profile_users_path(current_user)
    else
      new_session_path(resource_name)
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  # cookies[:login_method] = "google"
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def edit_user
    self.resource = resource_class.new
    respond_to do |format|
      format.turbo_stream
    end
  end

  def edit_city
    self.resource = resource_class.new
    respond_to do |format|
      format.turbo_stream
    end
  end

  def after_update_path_for(resource)
    # 自分で設定した「マイページ」へのパス
    profile_users_path
  end
  # protected

  def update_resource(resource, params)
      resource.update_without_password(params)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super do |resource|
      cookies[:login_method] = resource.provider.present? ? "google" : "normal"
      flash[:notice] = "Welcome To ColorMirror!! #{ current_user.name }さん"
    end
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected
  # ログアウト後のリダイレクト先
  def after_sign_out_path_for(resource)
    root_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def reminder
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/views/users/_line_modal.html.erb
<div data-controller="modal" data-modal-target="modal" data-action="click->modal#close" class="flex items-center justify-center sm:p-8 p-4 fixed inset-0 bg-black bg-opacity-50 z-20">
    <div class="flex items-center justify-center bg-gradient-diagonal rounded-xl shadow-lg sm:p-8 p-4 relative sm:max-w-3xl max-h-96 h-full w-full">
        <div class="w-full h-full flex flex-col justify-center items-center space-y-4">
            <!-- Header -->
            <h2 class="text-xl font-bold mb-4">LINE連携の方法</h2>

            <!-- 友だち追加 -->
            <div class="mb-4 max-w-xl flex justify-around items-center glass p-2">
                <p class="text-sm mb-1">公式LINEを友だち追加（QRコード）</p>
                <div class="w-[120px] h-[40px]">
                    <a href="https://lin.ee/G7xVc73B" class="rounded-md"><img src="https://scdn.line-apps.com/n/line_add_friends/btn/ja.png" alt="友だち追加" height="24" border="0"></a>
                </div>
            </div>

            <!-- トークン表示 -->
            <div class="flex items-center justify-between glass px-3 py-2 rounded join max-w-md w-full">
                <input type="text" id="line-token" data-modal-target="token" value="<%= current_user.line_token %>" readonly class="input join-item bg-transparent text-xl mr-3 focus:outline-none" />
                <button data-action="click->modal#copyToken" data-modal-target="copyButton" class="join-item transition">
                    <i class="fa-regular fa-copy fa-2xl"></i>
                </button>

            </div>

            <!-- 使い方 -->
<div class="text-sm text-gray-700 neumorphism mt-4 p-2">
  <ul class="space-y-2">
    <li class="flex items-start">
      <span class="text-green-500  mr-2">
        <i class="fas fa-check-circle"></i>
      </span>
      <span>「友達追加」ボタンからQRコードを読み取り、公式LINEを友達に追加します。</span>
    </li>
    <li class="flex items-start">
      <span class="text-green-500  mr-2">
        <i class="fas fa-check-circle"></i>
      </span>
      <span>表示されたトークンをコピーして、LINEトークルームに送信してください。</span>
    </li>
    <li class="flex items-start">
      <span class="text-green-500  mr-2">
        <i class="fas fa-check-circle"></i>
      </span>
      <span>通知のON/OFFは「リマインダ設定」「リマインダ解除」の送信で切り替え可能です。</span>
    </li>
  </ul>
</div>


        </div>




        <button type="button" data-action="click->modal#close" class="text-gray-500 hover:scale-125 sm:text-3xl text-lg absolute top-0 right-0 sm:p-4 p-2 z-20">
          ✖️
        </button>
    </div>
</div>

app/views/users/reminder.turbo_stream.erb
<turbo-stream action="update" target="line-modal">
    <template>
    <div data-controller="modal" data-modal-target="modal">
      <%= render partial: "line_modal", formats: [:html] %>
    </div>
    </template>
</turbo-stream>

app/views/users/show.html.erb
<div class="flex flex-col items-center sm:p-8 p-0 min-h-screen">
  <div class="bg-base-200 my-4 p-4 rounded-md flex items-center justify-between max-w-xl w-full">
    <p class="">友達追加をするとリマインダを受け取れます</p>
    <button type="button" class="rounded-md p-3">
      <%= link_to "友達追加はこちら", reminder_users_path, class:"hover:bg-emerald-600 bg-emerald-400 rounded-md p-3 text-white text-xs font-bold", data: { turbo_stream: true } %>
    </button>
</div>
<div id="profile" class="card max-w-3xl sm:w-full glass overflow-y-auto max-h-[80vh]">
    <figure class="px-4 pt-4 flex flex-col">
      <div class="avatar">
        <div class="w-24 h-24 rounded-full border-4 mx-auto mt-4 shrink-0 object-cover">
            <img class="" src="/images/onomatopoeia/アバター画像.png">
        </div>
      </div>
      <% if current_user.provider.present? %>
        <div class="badge bg-gradient-diagonal text-md max-w-sm sm:p-2 p-1 skeleton">Google連携中</div>
      <% end %>
    </figure>
    <div class="card-body items-center text-center">
        <h2 class="card-title"><%= current_user.name %></h2>
        <p class="text-base-content text-opacity-70">
            <%= current_user.email %>
            <%= current_user.prefecture %>
        </p>
        <div class="card-actions">
            <%= link_to "Eメールを編集する", edit_user_path, class: "text-base-content btn bg-white w-full", data: { turbo_stream: true } %>
            <%= link_to "居住都市を編集する", edit_city_path, class: "text-base-content btn bg-white w-full", data: { turbo_stream: true } %>
            <%= link_to "パスワードを編集する", reset_password_path, class: "text-base-content btn bg-white w-full", data: { turbo_stream: true } %>
        </div>
                <div class="sm:my-4 my-2 sm:py-2 py-0 border-y-2 mx-auto w-full">
            <%= link_to "アカウント削除", user_registration_path, class: "text-base-content btn bg-rose-500 text-white font-bold w-full", data: { turbo_method: :delete, turbo_confirm: "本当にアカウントを削除しますか" } %>
        </div>
    </div>
</div>
<div id="edit-modal" data-controller="modal" data-modal-target="modal"></div>
<div id="password-reset-modal" data-controller="modal" data-modal-target="modal"></div>
<div id="line-modal" data-controller="modal" data-modal-target="modal"></div>