config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/confirmation/resend", to: "users/confirmations#resend", as: :resend_confirmation
    get "users/confirmation/confirm", to: "users/confirmations#confirm", as: :confirm_confirmation
    get "users/password/reset_password", to: "users/passwords#reset_password", as: :reset_password
    get "users/registration/edit_user", to: "users/registrations#edit_user", as: :edit_user
    get "users/registration/edit_city", to: "users/registrations#edit_city", as: :edit_city
    delete "/users/unlink_google_account", to: "users/omniauth_callbacks#unlink_google_account", as: :unlink_google_account
  end
  resource :users, only: [ :show, :edit, :destroy, :update ] do
    get "profile", to: "users#show", as: "profile"
    get "reminder", to: "users#reminder", as: "reminder"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/home/privacy", to: "home#privacy", as: :privacy
  get "/home/rules", to: "home#rules", as: :rules
  get "colors/top" => "colors#top"

  resources :colors do
  collection do
    get "/colors/form", to: "colors#form", as: :form
  end
end

  resources :self_logs, only: [ :index, :show, :create, :destroy ] do
    member do
      get :ai_response
    end
    resources :weather_logs, only: [ :index, :show, :create, :destroy ]
    # get "colors/:id/response", to: "colors#response", as: :response
  end
  resources :analysis_results, only: [ :index, :show, :create, :destroy ]

  # chatbot機能
  get "chatbots/ask" => "chatbots#ask"
  post "chatbots/answer" => "chatbots#answer"

  # OpenWeatherAPI機能のルーティング
  get "weather", to: "weathers#index", as: :weather
  get "weather/show", to: "weathers#show", as: :show_weather, defaults: { format: :json }

  # JSからheatmap_dataへのエンドポイント
  get "heatmap", to: "result_maps#heatmap_data", as: :heatmap
  # JSからradar_map_dataへのエンドポイント
  get "map", to: "result_maps#map_data", as: :map
  # JSからopen AI へのエンドポイント
  post "/colors/analyze", to: "colors#analyze"
  # LINEルーティング
  post "/callback", to: "line#callback", as: :callback

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/views/shared/_before_menu.erb
  <div class="flex-none mr-8 relative z-50">
    <div class="drawer drawer-end">
      <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <!-- ドロワーメニューの開閉ボタン -->
        <label for="my-drawer-4" id="glass-drawer-toggle" class="drawer-button btn btn-ghost p-3 bg-white/10 backdrop-blur-md text-white rounded-full shadow-lg">
          <i class="fa-solid fa-ellipsis-vertical text-3xl md:text-xl"></i>
        </label>
      </div>
      <div class="drawer-side">
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <ul id="glass-drawer-menu" class="menu min-h-full max-w-md w-full p-4 bg-white/30 backdrop-blur-md shadow-lg transform -translate-x-full transition-transform mt-16 space-y-4 text-white">
          <!-- Sidebar content here -->

              <div class="flex items-center gap-x-4 justify-start border-solid border-b-2 border-bg-white/30 pb-2">
                <span class="w-10 h-10 flex items-center justify-center">
                  <i class="fa-solid fa-house-laptop text-2xl font-bold"></i>
                </span>
                  <li><%= link_to "ログイン", user_session_path, class:"hover:bg-white/20" %></li>
              </div>

              <div class="flex items-center gap-x-4 justify-start">
                <i class="fa-solid fa-user-lock block text-2xl w-10 h-10 font-bold"></i>
                  <li><a href="" class="hover:bg-white/20">プライバシーポリシー</a></li>
              </div>
              <div class="flex items-center gap-x-4 justify-start">
                  <i class="fa-solid fa-lock block text-2xl w-10 h-10 font-bold"></i>
                  <li><a href="" class="hover:bg-white/20">利用規約</a></li>
              </div>
              <div class="flex items-center gap-x-4 justify-start">
                  <i class="fa-regular fa-envelope block text-2xl w-10 h-10 font-bold"></i>
                  <li><a href="" class="hover:bg-white/20">お問い合わせ</a></li>
              </div>

              <div class="flex flex-col items-center justify-center text-center border-solid border-t-2 border-bg-white/30 mt-2 pt-4">
                <p class="font-bold text-lg">©︎ 2025年 - ColorMirror</p>
                <div class="m-2">
                <a href=""class="mr-4">X</a>
                <a href="">GitHub</a>
                </div>
              </div>

        </ul>
      </div>
    </div>
  </div>

app/views/shared/_before_menu.html.erb
  <div class="mr-8 relative z-50 min-h-full">
    <div class="drawer drawer-end">
      <input id="my-drawer-4" type="checkbox" class="drawer-toggle" />
      <div class="drawer-content">
        <!-- ドロワーメニューの開閉ボタン -->
        <label for="my-drawer-4" id="glass-drawer-toggle" class="drawer-button btn btn-ghost p-3 bg-white/10 backdrop-blur-md text-white rounded-full shadow-lg">
          <i class="fa-solid fa-ellipsis-vertical text-3xl md:text-xl"></i>
        </label>
      </div>
      <div class="drawer-side">
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <ul id="glass-drawer-menu" class="menu min-h-full max-w-md w-full p-6 bg-white/30 backdrop-blur-md shadow-lg transform -translate-x-full transition-transform space-y-4 text-white">
          <!-- Sidebar content here -->
          <div class="block sm:hidden">
            <li>
              <label for="my-drawer-4" class="drawer-button text-right block">
                <i class="fa-regular fa-circle-xmark text-5xl text-white"></i>
              </label>
            </li>
          </div>
              <% if user_signed_in? %>
                <div class="flex items-center gap-x-4">
                  <span class="w-10 h-10 flex items-center justify-center">
                    <i class="fa-solid fa-right-from-bracket text-2xl font-bold"></i>
                  </span>
                  <li>
                    <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class:"hover:bg-white/20" %>
                  </li>
                </div>
                <div class="flex items-center gap-x-4 justify-start border-solid border-b-2 border-bg-white/30 pb-2">
                  <span class="w-10 h-10 flex items-center justify-center">
                    <i class="fa-solid fa-house-laptop text-2xl font-bold"></i>
                  </span>
                    <li><%= link_to "マイページ", profile_users_path, class:"hover:bg-white/20" %></li>
                </div>
                <div class="flex items-center gap-x-4 justify-start">
                  <span class="w-10 h-10 flex items-center justify-center">
                    <i class="fa-solid fa-chart-simple block text-2xl font-bold"></i>
                  </span>
                    <li><%= link_to "振り返り", analysis_results_path, class:"hover:bg-white/20" %></li>
                </div>
              <% end %>
              <div class="flex items-center gap-x-4 justify-start">
                <i class="fa-solid fa-user-lock  text-2xl  font-bold"></i>
                  <li>
                    <%= link_to"プライバシーポリシー", privacy_path, class:"hover:bg-white/20" %>
                  </li>
              </div>
              <div class="flex items-center gap-x-4 justify-start">
                  <i class="fa-solid fa-lock  text-2xl  font-bold"></i>
                  <li>
                  <%= link_to"利用規約", rules_path, class:"hover:bg-white/20" %>
                  </li>
              </div>
              <div class="flex items-center gap-x-4 justify-start">
                  <i class="fa-regular fa-envelope  text-2xl font-bold"></i>
                  <li>
                    <%= link_to "お問い合わせ", form_colors_path, class:"hover:bg-white/20" %>
                  </li>
              </div>

              <div class="flex flex-col items-center justify-center text-center border-solid border-t-2 border-bg-white/30 mt-2 pt-4">
                <p class="font-bold text-lg">copyright ©︎ 2025 - ColorMirror</p>
              </div>

        </ul>
      </div>
    </div>
  </div>

app/views/shared/_cards.html.erb
    <div id="STEP2" class="mx-auto text-center hover:shadow-xl my-4 max-h-screen overflow-y-auto">
    <h2 class="text-lg font-bold text-base-300 mb-4">下のカードから今の気分を選んでください</h2>
    <div class="grid grid-cols-1 md:grid-cols-5 justify-between gap-4 w-full mx-auto p-6 max-h-screen overflow-y-auto">
    <%# ワクワクcard %>
        <button type="button" class="flip-card neumorphism w-full max-w-xs h-80 perspective relative bg-none border-none rounded-lg shadow-lg  bg-transparent p-0 mood-button" data-mood="ワクワク">
            <div class="flip-card-inner transition-transform transform-style preserve-3d relative w-full h-full">
                <!-- 表面 -->
                <div class="flip-card-front absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center" style="background-image: url('/images/onomatopoeia/ワクワクfront.jpg');">
                    <span class="text-white text-lg font-bold">ワクワク</span>
                </div>
                <!-- 裏面 -->
                <div class="flip-card-back absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center rotate-y-180 font-bold"
                    style="background-image: url('/images/onomatopoeia/ワクワクback.jpg');">
                    <span class="text-white text-lg font-bold">この気分を選択中</span>
                </div>
            </div>
        </button>
    <%# ムカムカcard %>
        <button type="button" class="flip-card neumorphism w-full max-w-xs h-80 perspective relative bg-none border-none rounded-lg shadow-lg  bg-transparent p-0 mood-button" data-mood="ムカムカ">
            <div class="flip-card-inner transition-transform transform-style preserve-3d relative w-full h-full">
                <!-- 表面 -->
                <div class="flip-card-front absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center" style="background-image: url('/images/onomatopoeia/ムカムカfront.jpg');">
                    <span class="text-white text-lg font-bold">ムカムカ</span>
                </div>
                <!-- 裏面 -->
                <div class="flip-card-back absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center rotate-y-180 font-bold"
                    style="background-image: url('/images/onomatopoeia/ムカムカback.jpg');">
                    <span class="text-white text-lg font-bold">この気分を選択中</span>
                </div>
            </div>
        </button>
    <%# モヤモヤcard %>
        <button type="button" class="flip-card neumorphism w-full max-w-xs h-80 perspective relative bg-none border-none rounded-lg shadow-lg  bg-transparent p-0 mood-button" data-mood="モヤモヤ">
            <div class="flip-card-inner transition-transform transform-style preserve-3d relative w-full h-full">
                <!-- 表面 -->
                <div class="flip-card-front absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center" style="background-image: url('/images/onomatopoeia/モヤモヤfront.jpg');">
                    <span class="text-white text-lg font-bold">モヤモヤ</span>
                </div>
                <!-- 裏面 -->
                <div class="flip-card-back absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center rotate-y-180 font-bold"
                    style="background-image: url('/images/onomatopoeia/モヤモヤback.jpg');">
                    <span class="text-white text-lg font-bold">この気分を選択中</span>
                </div>
            </div>
        </button>
    <%# ホッとcard %>
        <button type="button" class="flip-card neumorphism w-full max-w-xs h-80 perspective relative bg-none border-none rounded-lg shadow-lg  bg-transparent p-0 mood-button" data-mood="ホッと">
            <div class="flip-card-inner transition-transform transform-style preserve-3d relative w-full h-full">
                <!-- 表面 -->
                <div class="flip-card-front absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center" style="background-image: url('/images/onomatopoeia/ホッとfront.jpg');">
                    <span class="text-white text-lg font-bold">ホッと</span>
                </div>
                <!-- 裏面 -->
                <div class="flip-card-back absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center rotate-y-180 font-bold"
                    style="background-image: url('/images/onomatopoeia/ホッとback.jpg');">
                    <span class="text-white text-lg font-bold">この気分を選択中</span>
                </div>
            </div>
        </button>
    <%# その他card %>
        <button type="button" class="flip-card neumorphism w-full max-w-xs h-80 perspective relative border-none rounded-lg shadow-lg  bg-transparent p-0 mood-button" data-mood="わからない">
            <div class="flip-card-inner transition-transform transform-style preserve-3d relative w-full h-full">
                <!-- 表面 -->
                <div class="flip-card-front absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center"
                style="background-image: url('/images/onomatopoeia/わからない.jpg');">
                    <span class="text-white text-lg font-bold">わからない</span>
                </div>
                <!-- 裏面 -->
                <div class="flip-card-back absolute w-full h-full rounded-lg shadow-lg bg-cover bg-center flex items-center justify-center rotate-y-180 font-bold">
                    <span class="text-white text-lg font-bold">この気分を選択中</span>
                </div>
            </div>
        </button>

        </div>
    </div>

app/views/shared/_chart.html.erb
<canvas id="myChart" class="rounded-lg shadow-lg p-4 neumorphism"></canvas>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id= "error_explanation" class="alert alert-danger">
        <ul class="mb-0">
        <% object.errors.each do |error| %>
            <li><%= error.full_message %></li>
        <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div,
    simple_format(message),
    class: "alert alert-#{message_type == "notice" ? "success" : "danger"}"
  ) %>
<% end %>

app/views/shared/_footer.html.erb
<div class="btm-nav bg-footer-gradient-diagonal h-16 fixed z-50">
  <%= link_to new_color_path, class: active_class_by_controller_and_action("colors", "new") do %>
  <button class="flex flex-col items-center justify-center border-none primary-content">
    <i class="fa-solid fa-pencil fa-2xl p-4"></i>
    <span>記録する</span>
  </button>
  <% end %>
  <%= link_to colors_path, class: active_class_by_controller_and_action("colors", "index") do %>
  <button class="flex flex-col items-center justify-center border-none primary-content">
      <i class="fa-solid fa-book fa-2xl p-4"></i>
      <span>見る</span>
  </button>
  <% end %>
<%= link_to analysis_results_path, class: active_class_by_controller_and_action("analysis_results", "index") do %>
  <button class="flex flex-col items-center justify-center border-none primary-content">
    <i class="fa-solid fa-database fa-2xl p-4"></i>
    <span>振り返る</span>
  </button>
<% end %>
</div>

app/views/shared/_form.html.erb
<%= form_with model: @color, url: colors_path, method: :post, scope: :color,local: true, data: { turbo: false } do |f|%>
<%= render 'shared/error_messages', object: f.object %>
<div data-controller="carousel" class="swiper sm:mb-8 mb-4 sm:p-8 p-4 bg-opacity-50 z-20 flex flex-col ">
    <div class="swiper-wrapper">
        <div id=STEP1/2 data-carousel-target="slide" class="swiper-slide  p-6 hover:shadow-lg  glass relative min-h-screen">
            <div class="font-maru uppercase tracking-wide text-center text-emerald-500 font-bold text-4xl items-center my-4 sm:my-2">STEP 1/2</div>
            <%# sign up時の居住地を初期値にセット %>
            <%= f.hidden_field :city, id: "city", value: @city, class: "hidden", required: true %>
            <div id="weather_image" class="max-w-full w-full rounded-xl shadow-lg mx-auto overflow-x-auto">
                <%= render "shared/weather_card" %>
                <div class="flex justify-between mt-4">
                    <button
                        class="swiper-button-next-custom absolute hidden sm:flex fixed right-0 top-1/2  -translate-y-1/2 transform text-cyan-400 bg-gray-800 hover:bg-white rounded-full p-2 focus:outline-none">
                        <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                        </svg>
                    </button>
                </div>
            </div>
            <%# 天気カードから取得したパラメーター %>
            <div class="hidden_fields">
                <%= f.hidden_field :weather_name, id: "weather_name" %>
                <%= f.hidden_field :description, id: "description" %>
                <%= f.hidden_field :temperature, id: "temperature" %>
                <%= f.hidden_field :temp_max, id: "temp_max" %>
                <%= f.hidden_field :temp_min, id: "temp_min" %>
                <%= f.hidden_field :weather_pressure, id: "weather_pressure" %>
                <%= f.hidden_field :weather_icon, id: "weather_icon" %>
            </div>

            <div>
                <%= render "shared/cards" %>
                <%= f.hidden_field :mood, id: "selected-mood", required: true %>
            </div>
            <div class="mx-auto max-w-sm w-full">
                <button type="button" class="swiper-button-next-custom w-full bg-success text-white text-md font-maru  p-2 sm:p-4 my-4  rounded-2xl shadow-lg hover:opacity-70 animate-bounce hover:animate-none">次のステップへ</button>
            </div>
        </div>

        <div id="STEP2/2" data-carousel-target="slide" class="swiper-slide p-6 glass min-h-screen">
                <div class="font-maru uppercase tracking-wide text-center text-emerald-500 font-bold text-4xl items-center my-4 sm:my-2">STEP 2/2</div>
                <div id="display-confirmation"></div>
                <div class="flex flex-col justify-center mx-auto gap-4 p-4 max-w-2xl ">
                    <button type="button" id="generate-colors" data-carousel-target="generate" class="font-maru bg-info text-white border-none font-bold hover:shadow-xl w-full px-4 py-2 rounded-2xl">
                        セルフカラーを生成する
                    </button>

                    <div id="color-suggest" class="grid grid-flow-row sm:grid-cols-2 space-x-4"></div>
                    <%= f.submit class: "bg-secondary bg-info text-white border-none font-bold hover:shadow-xl w-full px-4 py-2 rounded-2xl", data: { action: "click->loading#show" } %>
                </div>
            <button
                class="swiper-button-prev-custom absolute hidden sm:flex left-0 top-1/3 -translate-y-1/2 transform text-cyan-400 bg-gray-800 hover:bg-white rounded-full p-2 focus:outline-none">
                <svg class="w-12 h-12 rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
                </svg>
            </button>
                <%= f.hidden_field :color_name, id: "color_name", required: true %>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_header.html.erb
<div class="bg-gradient-diagonal flex items-start justify-between p-4 h-20">
    <%= link_to root_path, class: "hover:opacity-50" do %>
        <p class="maru text-4xl font-bold text-white">ColoMirror</p>
    <% end %>
    <% if user_signed_in? %>
        <%= render "shared/drawer_menu",class: "" %>
    <% else %>
        <%= render "shared/before_menu" %>
      <% end %>
</div>

app/views/shared/_heatmap.html.erb
<div class="lg:w-full w-[400px] flex justify-center lg:items-center sm:flex-col flex-col-reverse">
  <div id="cal-heatmap" class="overflow-scroll neumorphism max-w-screen-lg w-full h-full p-4 mx-auto my-6 rounded-lg shadow-md"></div>

  <!-- 凡例 -->
  <div class="flex items-center sm:gap-6 gap-2 sm:mt-6 mt-3 text-[10px] sm:text-xs mx-auto">
    <div class="flex flex-col items-center gap-1">
      <span class="text-gray-500">&nbsp;</span>
      <div class="sm:w-8 w-4 sm:h-8 h-4 rounded bg-[##FF5C7A]"></div>
    </div>
    <div class="flex flex-col items-center gap-1">
      <span class="text-gray-400">雨 ☔️</span>
      <div class="sm:w-8 w-4 sm:h-8 h-4 rounded bg-[#191970]"></div>
    </div>
    <div class="flex flex-col items-center gap-1">
      <span class="text-gray-500">曇り ☁︎</span>
      <div class="sm:w-8 w-4 sm:h-8 h-4 rounded bg-[#A9A9A9]"></div>
    </div>
    <div class="flex flex-col items-center gap-1">
      <span class="text-gray-400">晴れ 🌞</span>
      <div class="sm:w-8 w-4 sm:h-8 h-4 rounded bg-[#FF8C42]"></div>
    </div>

  </div>
</div>

app/views/shared/_oauth_form.html.erb
<%= form_with url: user_google_oauth2_omniauth_authorize_path(type: "login", prompt: "none"), method: :post, data: { turbo: false }, class: "space-y-4" do %>
  <%= hidden_field_tag :type, "login" %>
<button class="gsi-material-button block mx-auto">
  <div class="gsi-material-button-state"></div>
  <div class="gsi-material-button-content-wrapper">
    <div class="gsi-material-button-icon">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
        <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
        <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
        <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
        <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
        <path fill="none" d="M0 0h48v48H0z"></path>
      </svg>
    </div>
    <span class="gsi-material-button-contents">Sign in with Google</span>
    <span style="display: none;">Sign in with Google</span>
  </div>
</button>
<% end %>

app/views/shared/_oauth_new.html.erb
<%= form_with url: user_google_oauth2_omniauth_authorize_path(type: "login", prompt: "select_account"), method: :post, data: { turbo: false }, class: "space-y-4" do %>
  <%= hidden_field_tag :type, "login" %>
<button class="gsi-material-button block mx-auto">
  <div class="gsi-material-button-state"></div>
  <div class="gsi-material-button-content-wrapper">
    <div class="gsi-material-button-icon">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
        <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
        <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
        <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
        <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
        <path fill="none" d="M0 0h48v48H0z"></path>
      </svg>
    </div>
    <span class="gsi-material-button-contents">Sign in with Google</span>
    <span style="display: none;">Sign in with Google</span>
  </div>
</button>
<% end %>

app/views/shared/_response.html.erb
<% if @response.present? %>
<div class="grid grid-cols-2 gap-4">
    <div class="border-l-4 border pl-4 py-2 text-white bg-red-400 rounded-lg mb-2">
        <h3 class="font_bold text-sm ">気分の分析</h3>
        <p class=""><%= simple_format(@response.color_analysis) %></p>
    </div>

    <div class="border-l-4 border pl-4 py-2 bg-cyan-400 rounded-lg">
        <h3 class="text-bold text-sm">天気との分析</h3>
        <p class=""><%= simple_format(@response.weather_analysis) %></p>
    </div>
    <% else %>
    <h1>今日はまだ、気分の登録をされていないため、コメントが生成されていません</h1>
    <% end %>
</div>

app/views/shared/_weather_card.html.erb
<div class="flex flex-col">
  <div class="flex items-center justify-center gap-4">
    <p class="text-center text-white tracking-wider text-xl animate-fade-in-text block my-4">現在地の環境を設定</p>
      <span class="tooltip tooltip-left sm:tooltip-right custom-tooltip" data-tip="居住都市を登録していれば天気情報は自動取得されます"><i class="fa-solid fa-circle-exclamation text-base-300 text-lg cursor-pointer z-20"></i></span>
  </div>

    <%# お天気カードUI %>
    <div id="display-weather" class=""></div>

</div>