config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/confirmation/resend", to: "users/confirmations#resend", as: :resend_confirmation
    get "users/confirmation/confirm", to: "users/confirmations#confirm", as: :confirm_confirmation
    get "users/password/reset_password", to: "users/passwords#reset_password", as: :reset_password
    get "users/registration/edit_user", to: "users/registrations#edit_user", as: :edit_user
    get "users/registration/edit_city", to: "users/registrations#edit_city", as: :edit_city
    delete "/users/unlink_google_account", to: "users/omniauth_callbacks#unlink_google_account", as: :unlink_google_account
  end
  resource :users, only: [ :show, :edit, :destroy, :update ] do
    get "profile", to: "users#show", as: "profile"
    get "reminder", to: "users#reminder", as: "reminder"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/home/privacy", to: "home#privacy", as: :privacy
  get "/home/rules", to: "home#rules", as: :rules
  get "colors/top" => "colors#top"

  resources :colors do
  collection do
    get "/colors/form", to: "colors#form", as: :form
  end
end

  resources :self_logs, only: [ :index, :show, :create, :destroy ] do
    member do
      get :ai_response
    end
    resources :weather_logs, only: [ :index, :show, :create, :destroy ]
    # get "colors/:id/response", to: "colors#response", as: :response
  end
  resources :analysis_results, only: [ :index, :show, :create, :destroy ]

  # chatbot機能
  get "chatbots/ask" => "chatbots#ask"
  post "chatbots/answer" => "chatbots#answer"

  # OpenWeatherAPI機能のルーティング
  get "weather", to: "weathers#index", as: :weather
  get "weather/show", to: "weathers#show", as: :show_weather, defaults: { format: :json }

  # JSからheatmap_dataへのエンドポイント
  get "heatmap", to: "result_maps#heatmap_data", as: :heatmap
  # JSからradar_map_dataへのエンドポイント
  get "map", to: "result_maps#map_data", as: :map
  # JSからopen AI へのエンドポイント
  post "/colors/analyze", to: "colors#analyze"
  # LINEルーティング
  post "/callback", to: "line#callback", as: :callback

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :self_logs, dependent: :destroy
  has_many :responses, through: :self_logs, dependent: :destroy
  has_many :weather_logs, through: :self_logs, dependent: :destroy

  validates :color_name, presence: true

    # 感情ごとのスコアマッピング
    MOOD_SCORE = {
      "ホッと" => 5,
      "ワクワク" => 4,
      "わからない" => 3,
      "モヤモヤ" => 2,
      "ムカムカ" => 1
    }.freeze

  def mood_score
    MOOD_SCORE[mood] || 0
  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :authenticate_user!, only: [ :index, :new ]
  def top;end

  def index
    @start_date = Date.today.beginning_of_week
    @end_date = Date.today.end_of_week
    @week_colors = Color
      .joins(:self_logs)
      .includes(self_logs: [ :response, :weather_log ])
      .where(self_logs: { user_id: current_user.id })
      .where(colors: { created_at: @start_date.beginning_of_day..@end_date.end_of_day })
      .select("DISTINCT ON (DATE(colors.created_at)) colors.*")
      .order("DATE(colors.created_at), colors.created_at DESC")
  end

  def new
    @color = ColorForm.new
    @city = current_user.prefecture&.text
  end

  def create
    # newアクションで作成したオブジェクトにformオブジェクトインスタンスを格納
    @color = ColorForm.new(color_params)

    # formオブジェクトで処理されたデータを保存
    if @color.save
      flash[:notice] = "本日のデータは登録し、コメントを生成しました"
      self_log = @color.color.self_logs.find_by(user_id: current_user.id)

      # Jobを呼ぶコードを書く
      # promptとして使うデータを変数に格納
      prompt = color_params.slice(:color_name, :mood)
      weather_data = color_params.slice(:weather_name, :weather_pressure, :temperature)

      AiGenerationJob.perform_later(prompt, weather_data, self_log.id, @color.color.id, current_user.id)
      redirect_to colors_path
    else
      flash.now[:alert] = "保存失敗、情報が不足している可能性があります"
      render :new,  status: :unprocessable_entity
    end
  end

  def analyze
    mood = params[:mood]
    weather = params[:weather]

    suggested_colors = AiColorService.generate_color(mood, weather)
    render json: { colors: suggested_colors }
  end
  def form;end

  private

  def set_color
    @color = current_user.colors.find(params[:id])
  end
  def color_params
    params.require(:color).permit(:color_name, :mood, :weather_name, :description, :temperature, :temp_max, :temp_min, :weather_pressure, :weather_icon, :city, :color_analysis, :weather_analysis, :self_log_id).merge(user_id: current_user.id)
  end
end

app/views/colors/_card.html.erb
<% log = color.self_logs.order(created_at: :desc).first  %>
<% weather_image = WeatherHelper.weather_image(log&.weather_log.weather_icon) %>

<div class="card-flip card-hover neumorphism h-64 w-full rounded-xl shadow-xl overflow-hidden text-white" style="background-image: url(<%= weather_image %>); background-size: cover; background-position: center;">
    <div class="bg-black bg-opacity-20 w-full h-full p-4 flex flex-col justify-between">
    <!-- 上部：日付・気分 -->
        <div>
            <p class="text-sm"><%= color.created_at.strftime("%-m/%-d（#{%w[日 月 火 水 木 金 土][color.created_at.wday]}）") %></p>
            <div class="flex items-center space-x-2 text-sm">
                <span><%= OnomatopeiaHelper.mood_for_icon(color.mood) %></span>
                <h2 class="text-xl font-bold"><%= color.mood %></h2>
            </div>
            <div class="flex items-center space-x-2 text-sm">
                <span><%= WeatherHelper.emoji_for_icon(log.weather_log.weather_icon) %></span>
                <span><%= log.weather_log.description %></span>
            </div>
        </div>

        <!-- 中央：カラー丸 -->
        <div class="mx-auto w-16 h-16 rounded-full border-2 border-white shadow-inner" style="background-color: <%= color.color_name %>;"></div>

        <!-- 下部：ボタン -->
        <div class="text-center">
            <%= link_to "AIのレスポンスを見る", ai_response_self_log_path(log.id), data: { turbo_stream: true }, class: "mt-4 px-4 py-2 bg-white text-gray-800 text-sm rounded-full font-semibold hover:bg-gray-200 transition" %>
        </div>
    </div>
</div>

app/views/colors/form.html.erb
<div class="m-6">
<iframe class="mx-auto text-xs aspect-auto max-w-full max-h-full" src="https://docs.google.com/forms/d/e/1FAIpQLSdm8zMudDTuu8Esgjnh_Z95tiXwCUZl_P69ZQPC9BpLVaf0xw/viewform?embedded=true"
width="640" height="1283" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>
</div>

app/views/colors/index.html.erb
<div class="flex flex-col items-center justify-center sm:px-4 sm:py-8 px-2 py-4 sm:space-y-10 space-y-5">

  <div class="text-center">
      <h2 class="text-3xl font-bold">今週の記録一覧</h2>
      <p class="text-sm text-gray-500"><%= @start_date.strftime("%-m/%-d") %> 〜 <%= @end_date.strftime("%-m/%-d") %></p>
  </div>
  <div class="max-w-7xl w-full mx-auto bg-slate-200 shadow-lg rounded-2xl p-8">
    <section class="glass overflow-hidden w-full">

      <% if @week_colors.present? %>
        <div class=" px-4 sm:px-8 md:px-12 mx-auto py-12 lg:py-24">

          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
            <% @week_colors.first(4).each do |color| %>
              <%= render partial: "colors/card", locals: { color: color } %>
            <% end %>
          </div>
          <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
            <% @week_colors.drop(4).each do |color| %>
              <%= render partial: "colors/card", locals: { color: color } %>
            <% end %>
          </div>

      <% else %>
        <p class="text-center text-gray-500">今週の記録はありません</p>
      <% end %>
    </section>
  </div>
</div>
<div id="response-modal"></div>

app/views/colors/new.html.erb
<div class="form_area">
    <%= render 'shared/form', color: @color %>
</div>