config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    post "users/confirmation/resend", to: "users/confirmations#resend", as: :resend_confirmation
    get "users/confirmation/confirm", to: "users/confirmations#confirm", as: :confirm_confirmation
    get "users/password/reset_password", to: "users/passwords#reset_password", as: :reset_password
    get "users/registration/edit_user", to: "users/registrations#edit_user", as: :edit_user
    get "users/registration/edit_city", to: "users/registrations#edit_city", as: :edit_city
    delete "/users/unlink_google_account", to: "users/omniauth_callbacks#unlink_google_account", as: :unlink_google_account
  end
  resource :users, only: [ :show, :edit, :destroy, :update ] do
    get "profile", to: "users#show", as: "profile"
    get "reminder", to: "users#reminder", as: "reminder"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index"
  get "/home/privacy", to: "home#privacy", as: :privacy
  get "/home/rules", to: "home#rules", as: :rules
  get "colors/top" => "colors#top"

  resources :colors do
  collection do
    get "/colors/form", to: "colors#form", as: :form
  end
end

  resources :self_logs, only: [ :index, :show, :create, :destroy ] do
    member do
      get :ai_response
    end
    resources :weather_logs, only: [ :index, :show, :create, :destroy ]
    # get "colors/:id/response", to: "colors#response", as: :response
  end
  resources :analysis_results, only: [ :index, :show, :create, :destroy ]

  # chatbot機能
  get "chatbots/ask" => "chatbots#ask"
  post "chatbots/answer" => "chatbots#answer"

  # OpenWeatherAPI機能のルーティング
  get "weather", to: "weathers#index", as: :weather
  get "weather/show", to: "weathers#show", as: :show_weather, defaults: { format: :json }

  # JSからheatmap_dataへのエンドポイント
  get "heatmap", to: "result_maps#heatmap_data", as: :heatmap
  # JSからradar_map_dataへのエンドポイント
  get "map", to: "result_maps#map_data", as: :map
  # JSからopen AI へのエンドポイント
  post "/colors/analyze", to: "colors#analyze"
  # LINEルーティング
  post "/callback", to: "line#callback", as: :callback

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  # mount MissionControl::Jobs::Engine, at: "/jobs"
end

app/controllers/chatbots_controller.rb
class ChatbotsController < ApplicationController
  protect_from_forgery

  def ask # ユーザーがアクセスして質問を入力するページを表示
  end

  def answer # ユーザーが質問を入力して送信すると、質問をOpenAIに送信して回答を取得
    prompt = params[:question] # ユーザーが入力した質問を取得
    response = ::ChatbotService.new.fetch_response(prompt)
    if response["choices"] && response["choices"][0] && response["choices"][0]["message"]
      @answer = response["choices"][0]["message"]["content"]
    else
      @answer = "回答が見つかりませんでした"
    end
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/views/chatbots/answer.turbo_stream.erb
<%= turbo_stream.append "chatbox" do %>
  <div class="chat chat-end">
    <div class="chat-header text-xs sm:text-base">
      <%= current_user.name %>
    </div>
    <div class="chat-bubble bg-green-300 max-w-xs mx-2 py-2 px-4 rounded-lg relative text-xs sm:text-base">
      <div><%= params[:question] %></div>
    </div>
  </div>

  <div class="chat chat-start">
    <div class="chat-header text-white text-xs sm:text-base">
        AI chatbot
    </div>
    <div class="chat-bubble bg-amber-300 max-w-xs mx-2 py-2 px-4 rounded-lg relative text-xs sm:text-base">
      <div><%= @answer %></div>
      <div class="absolute w-3 h-3 bg-amber-300 bottom-0 right-2 transform translate-y-1/2 rotate-45"></div>
    </div>
  </div>
<% end %>

app/views/chatbots/ask.html.erb
<div class="container mx-auto mt-20 min-h-screen flex flex-col">
  <h1 class="text-2xl sm:text-3xl font-bold text-center mb-8">AI Chatbot</h1>
  <p class="text-center text-xs sm:text-base">今日の気分や天候について気になることがありますか？</p>
  <p class="text-center text-xs sm:text-base">AI Chatbotに質問してみましょう！</p>

  <div class="card bg-blue-50 w-2/3 mx-auto flex flex-col justify-between shadow-xl rounded-lg p-6 mt-8 mb-4 flex-grow">
    <div class="card-body text-center flex flex-col items-center justify-center flex-grow">
      <div id="chatbox" class="mt-4 w-full space-y-4 flex-grow">
        <div class="chat chat-start">
          <div class="chat-image avatar">

          </div>
          <div class="chat-header text-xs sm:text-base text-gray-500">
            AI chatbot
          </div>
          <div class="chat-bubble max-w-xs mx-2 py-2 px-4 rounded-lg relative text-xs sm:text-base bg-amber-300 text-white">
            <p>こんにちは！私はAI Chatbotです。何か質問があればお気軽にどうぞ！</p>
          </div>
        </div>
      </div>
    </div>
    <div class="fixed bottom-0 left-0 right-0 bg-white p-4 pb-20">
      <%= form_with( url: chatbots_answer_path, data: { controller: "form-reset", action: "turbo:submit-end->form-reset#reset", turbo_frame: "chatbot-form" }) do |f| %>
        <div class="form-group flex items-center space-x-4 w-full">
          <div class="mr-2 flex-grow">
            <%= f.text_area :question, placeholder: "聞きたい内容を入力してください", class: "input input-bordered w-full h-20 rounded text-sm" %>
          </div>
          <div>
            <%= f.submit "質問する", class: "bg-purple-300 hover:bg-purple-500 btn btn primary px-6 py-3 hover:shadow-sm hover:translate-y-0.5 transform transition rounded shadow-lg" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>